blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Support and questions
    url: https://github.com/SeaweedbrainCY/jellyfin-newsletter/discussions
    about: Ask and answer questions here.
  - name: â„¹ï¸ Current known issues
    url: https://github.com/SeaweedbrainCY/jellyfin-newsletter/issues
    about: Find information about currently known problems.
